### ISSUE TITLE
Chams not working, and always on ESP without editing?

### ISSUE THREAD

**Issue by ExactAkatsuki** [wiotq/Qotq#1]
Not sure if the always on GlowESP is antipasta or intentional, but you should change it to

`if(g_pEngine->GetLocalPlayer() && g_Settings.visuals.glow) g_pGlow->Start();`

in line 61 of Hooks.cpp

**Comment by wiotq** [comment]
Fixed chams and always on GlowESP.

It was'nt international, just typical mistake :D
