### ISSUE TITLE
ESP Text bug

### ISSUE THREAD

**Issue by Toemer** [wiotq/Qotq#2]
Money, Distance, Weapon. All seem to have a problem where the text will render in the upper left corner above the watermark.
![rzactz7](https://user-images.githubusercontent.com/33212486/35793862-531c2088-0a21-11e8-84eb-3780b8074a93.jpg)

**Comment by wiotq** [comment]
Fixed
https://github.com/wiotq/Qotq/blob/master/Qotq_CSGO/Qotq_CSGO/ESP.cpp#L13
