### ISSUE TITLE
Weapon ESP Wrong

### ISSUE THREAD

**Issue by PnxOfficial** [wiotq/Qotq#3]
https://gyazo.com/50a4a79c5e5eca3beb7072519636c182 🗡

**Comment by PnxOfficial** [comment]
https://gyazo.com/1bbc8bc77030bf22b356e906e4bd4b96

**Comment by left2x** [comment]
Same, i think volvo updated offset tree, so now you need to do like 
`GetOffset("DT_BaseAttributableItem", "m_AttributeManager", "m_Item", "m_iItemDefinitionIndex"); `
to get item denitions, but you can't get an offset using more than one prop name in this version
